
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


# PARA MOSTRAR LAS CONSULTAS SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# PARA NO INCLUIR EL TRACE CUANDO HAY ERRORES EN LA API
spring.web.error.include-stacktrace=never

# SECRET PARA EL TOKEN
api.security.token.secret=${JWT_SECRET:anomalia}

# CONFIGURACION DE ACTUATOR HEALTH CHECK
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# CONFIGURACION DE GEMINI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
